/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = (() => {
  try {
    return (import.meta as any).env?.VITE_SUPABASE_PROJECT_ID || "";
  } catch {
    return "";
  }
})();

export const publicAnonKey = (() => {
  try {
    return (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || "";
  } catch {
    return "";
  }
})();